Feature/allen/nft
rubixchain/rubixgoplatform pull request #229
Opened 2024-10-14 12:22 UTC by Allen-Cherian

Creation of NFT : 

The creation of NFT api takes the file which should be converted to NFT, along with the file metadata. The metadata can include any details regarding the file which is being converted to NFT. One mandatory key in the nft metadata file is “filename”, which is being used while transferring NFT.

API: http://localhost:20002/api/createnft

In this api the data is passed as form data the keys which we use are : 
1. “did” [Text] - The did of the node which creates the nft
2. “UserID”[Text] - The particular user id basically it can be name or anything of the organization, user or anything
3.”NFTFileInfo”[File] : The metadata of the file which is being given
4.”NFTFile”[File] : The particular file which is made into an NFT
5."Data"[Text] : Any data the creator wishes to put in while creating a NFT

Note : The metadata file which we are adding should be of json format and the mandatory key of “filename”:”Name of the nft file” should be there.  You can add any other keys as you wish, the size, anything else. But “filename” is a mandatory key

Command : createnft
Flags : 
-did - The did of the node
-userID - The user id of the user
-nftFileInfo - The path of the metadata of the particular NFT
-nftFilePath - The path of the file which is being made into an NFT 

-nftData - Any data the creator wishes to put in while creating a NFT
-port - The port of the node

Deploy NFT 

The Deploy NFT api is similar to the smart contract deployment. While deploying an NFT, the value of NFT is assigned as 1. The amount of tokens pledged for deploying any NFT is based on this value 1. 

API : http://localhost:20002/api/deploy-nft

In this api the data is passed as json. An example of the request body is given below:

 
{
    "NFT" :"Qmbr1isZLmSCVyi6iVJJn89pSCnwxGUFbpfHzTpyEUMKNC",
    "DID" : "bafybmid23tc2ddfsmxbb5h26cyiljkylbp7fjsgpbucxlm43vzbm5p2b7y",
    "QuorumType": 2
}

Command : deploy-nft
Flags : 
-nft
-did
-quorum Type
  
Transfer NFT 
Transfer nft is basically the transfer of ownership of the NFT. The value specified while transferring the NFT is assigned as the new value of that particular NFT. The pledging also happens based on that particular value. 

API : localhost:20002/api/transfer-nft

In this api the data is passed as json. An example of the request body is given below 
{
    "NFT":"Qmbr1isZLmSCVyi6iVJJn89pSCnwxGUFbpfHzTpyEUMKNC",
    "Owner":"bafybmid23tc2ddfsmxbb5h26cyiljkylbp7fjsgpbucxlm43vzbm5p2b7y",
    "Receiver":"bafybmidpuc3vcegwxjrr6xnvvwvt3txmhkjnvdgb2kbyvemilw4lptxlvm",
    "QuorumType":2,
    "Comment":"Test execute nft",
    "NFTValue":1.0,
"NFTData":"Any string value user wishes to add" 

}

Command : transfer-nft
Flags : 
-nft
-owner
-receiver
-quorumType
-comment
-nftValue
-nftData

Subscribe NFT
For receiving an NFT a receiver node must subscribe to that particular NFT. This is similar to the subscription of smart contracts.
API : http://localhost:20002/api/subscribe-nft

In this api the data is passed as json. An example of the request body is given below 
{
    "NFT":"Qmbr1isZLmSCVyi6iVJJn89pSCnwxGUFbpfHzTpyEUMKNC",
}

Command : subscribe-nft
Flags : 
-nft 
-port

Get NFT Token Chain Data 
This api will return the nft token chain data
API : localhost:20002/api/get-nft-token-chain-data
In this api the data is passed as json. An example of request body is given below : 
{
  "latest": true,
  "token": "Qmbr1isZLmSCVyi6iVJJn89pSCnwxGUFbpfHzTpyEUMKNC"
}

2024-10-16 06:47 UTC, arnabghose997 commented on server/server.go
> +	s.AddRoute(setup.APIGetNFTTokenChainData, "POST", s.AuthHandle(s.APIGetNFTTokenChainData, true, s.AuthError, false))
This API should be `GET` based as we are only trying to retrieve NFT token chain data

2024-10-16 07:18 UTC, arnabghose997 commented on setup/setup.go
> +	APIGetNFTTokenChain                 string = "/api/get-nft-token-chain"
A better endpoint name could be `/api/dump-nft-token-chain`. Refer this [comment](https://github.com/rubixchain/rubixgoplatform/pull/229/files#r1802492977)

2024-10-16 09:53 UTC, arnabghose997 commented on core/nft.go
> +	c.w.CreateNFT(&nftTokenDetails)
Handle the error for `c.w.CreateNFT(...)`

2024-10-16 09:55 UTC, arnabghose997 commented on core/nft.go
> +	}
The `err` here will always be nil. These lines must be removed

2024-10-16 11:15 UTC, arnabghose997 commented on rac/rac.go
> +
Since the block struct for NFT is similar to that of Smart Contracts, we can remove this struct

2024-10-16 11:57 UTC, arnabghose997 requested changes
@Allen-Cherian  Apart from the review comments left, following are some high level suggestions that needs to be incorporated:

1. `/api/get-nft-token-chain-data` should be a `GET` request and the same should be reflected in Swagger docs.

2. Following should be the `/api/create-nft` inputs:

```
1. did (required) : creator of NFT
2. metadata (required): a JSON file which contain all the info about the NFT
3. artifact (required) : file that represents the NFT
```
3. The casing of request params for every NFT endpoint, should follow snake_case convention, instead of camelCase or PascalCase.

4. Ensure that changes in every NFT Request params should reflect in their respective command flags as well. For instance, if the request param `NFTFileInfo` is changed to `metadata`, then the corresponding Create NFT command flag should also be changed to `metadata`.

5. `transfer-nft` should be changed to `execute-nft` and it should have two flows:

  - Ownership transfer: whenever the `receiver` field has DID in it
  - Internal State Change: NFT can undergo state change without the transfer of ownership.   The condition being that `receiver` field is empty.

2024-10-18 11:53 UTC, Allen-Cherian commented
All the requested changes have been done.
## Test Cases Tested :

1. Normal flow : A nft is created, deployed and executed. 
2. Execution from node 1 to node 2 : Works as exepected.
3. Execution from node 1 : The reciver parameter is kept as empty and nft is executed : Works as exepected.

2024-10-21 12:21 UTC, arnabghose997 requested changes
@Allen-Cherian  Based on our discussions, leaving down few suggestions:

1. Dealing with scenario where Receiver and Owner DIDs are present on the same node

    When a NFT ownership transfer is initiated from current Owner to Receiver, it proceeds successfully. However, when we attempt do the reverse thereafter, the transaction fails stating that NFT information was not found in `NFTTable`
    
    For sake of understanding, lets consider first owner as `A` and second owner as `B`.
    
    What happens during first transfer (from A to B) is that the state change for the NFT in `NFTTable` happens like: `DID_A (Status: 0)  ---> DID_A (Status: 4)`. When its time for the reverse transfer, we search for the NFT owned by `DID_B`, which according to the current situation, is not present.
    
    This situation is similar to RBT transfer between DIDs on the same DID.
    
    I believe the correct state transition in the `NFTTable` should happen like this: `DID_A (Status: 0)  ---> DID_B (Status: 0)`. We can refer to the usage of [TokenTransferred](https://github.com/rubixchain/rubixgoplatform/blob/main/core/wallet/token.go#L379) in dealing with this scenario

2. Usage of IPFS Get instead of IPFS Cat operation to fetch NFT files

    IPFS Cat essentially reads the content in Bytes, which makes it difficult to identify its actual file name at source. Using IPFS Get lets directly download the file associated with the IPFS Hash.
    
    One approach is to individually call `Get` on each NFT content hash. Another approach is to create a single hash for the NFT directory, instead of individually hashing the contents of the directory
    
3. Add the key for `NFTData` (key "13", refer `block/block.go`) in the `keyMapping` variable of `command/decodeTokenChain.go` file.

2024-10-29 22:55 UTC, arnabghose997 approved these changes

2024-10-30 07:04 UTC, merged